gateways:
  istio-ingressgateway:
    autoscaleMin: 20
    autoscaleMax: 20
    tolerations:
    - key: "scalers.istio"
      operator: "Equal"
      value: "dedicated"
      effect: "NoSchedule"
    nodeAffinity:
    - scalers.istio: dedicated
    podAntiAffinityTermLabelSelector:
    - key: istio
      operator: In
      values: pilot
      topologyKey: "kubernetes.io/hostname"
    - key: istio
      operator: In
      values: ingressgateway
      topologyKey: "kubernetes.io/hostname"

pilot:
  tolerations:
  - key: "scalers.istio"
    operator: "Equal"
    value: "dedicated"
    effect: "NoSchedule"
  nodeAffinity:
  - scalers.istio: dedicated
  podAntiAffinityTermLabelSelector:
  - key: istio
    operator: In
    values: pilot
    topologyKey: "kubernetes.io/hostname"
  - key: istio
    operator: In
    values: ingressgateway
    topologyKey: "kubernetes.io/hostname"
  autoscaleMin: 20
  autoscaleMax: 20

mixer:
  policy:
    enabled: false
  telemetry:
    enabled: false

