gateways:
  istio-ingressgateway:
    autoscaleMin: 80
    autoscaleMax: 80
    tolerations:
    - key: "scalers.istio"
      operator: "Equal"
      value: "dedicated"
      effect: "NoSchedule"
    nodeSelector:
      scalers.istio: dedicated
    podAntiAffinityTermLabelSelector:
    - key: istio
      operator: In
      values: ingressgateway
      topologyKey: "kubernetes.io/hostname"

pilot:
  autoscaleMin: 80
  autoscaleMax: 80
  tolerations:
  - key: "scalers.istio"
    operator: "Equal"
    value: "dedicated"
    effect: "NoSchedule"
  nodeSelector:
    scalers.istio: dedicated
  podAntiAffinityTermLabelSelector:
  - key: istio
    operator: In
    values: pilot
    topologyKey: "kubernetes.io/hostname"

prometheus:
  nodeSelector:
    scalers.istio: prometheus
  tolerations:
  - key: "scalers.istio"
    operator: "Equal"
    value: "prometheus"
    effect: "NoSchedule"

mixer:
  policy:
    enabled: false
  telemetry:
    enabled: false

